#!/usr/bin/env python3
"""
Batch upload multiple videos from a JSON config
Usage: python batch_upload.py videos.json
"""

import json
import sys
from pathlib import Path
from upload_video import YouTubeUploader

def load_videos_config(config_file):
    """Load video list from JSON"""
    with open(config_file, 'r') as f:
        return json.load(f)

def batch_upload(config_file):
    """Upload multiple videos"""
    videos = load_videos_config(config_file)

    uploader = YouTubeUploader(
        credentials_file='credentials.json',
        token_file='token.pickle'
    )

    print("[INFO] Authenticating...")
    uploader.authenticate()

    total = len(videos)
    success = 0
    failed = 0

    for i, video in enumerate(videos, 1):
        print(f"\n[{i}/{total}] Uploading: {video['title']}")

        video_id = uploader.upload_video(
            file_path=video['file_path'],
            title=video['title'],
            description=video.get('description', ''),
            tags=video.get('tags', []),
            category_id=video.get('category_id', '10'),
            privacy_status=video.get('privacy_status', 'unlisted')
        )

        if video_id:
            success += 1
            print(f"[OK] Uploaded: https://youtube.com/watch?v={video_id}")
        else:
            failed += 1
            print(f"[FAIL] Failed to upload")

    print(f"\n{'='*60}")
    print(f"BATCH UPLOAD COMPLETE")
    print(f"{'='*60}")
    print(f"Total: {total} | Success: {success} | Failed: {failed}")
    print(f"{'='*60}\n")

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python batch_upload.py <config.json>")
        print("\nExample config.json:")
        print(json.dumps([
            {
                "file_path": "clips/clip1.mp4",
                "title": "SUNO Clip 1",
                "description": "Generated by SUNO",
                "tags": ["suno", "music"],
                "privacy_status": "unlisted",
                "category_id": "10"
            }
        ], indent=2))
        sys.exit(1)

    batch_upload(sys.argv[1])
