#!/usr/bin/env python3
"""
Simple SUNO YouTube Uploader
Just edit video_config and run: python simple_upload.py
"""

import json
from upload_video import YouTubeUploader

# ═══════════════════════════════════════════════════════════════
# EDIT THESE VALUES BEFORE RUNNING
# ═══════════════════════════════════════════════════════════════

video_config = {
    'file_path': 'clips/test.mp4',               # Path to video file
    'title': 'SUNO AI Generated Music - Test',   # Video title
    'description': 'Generated by SUNO AI automation system',  # Video description
    'tags': ['suno', 'ai-music', 'automation'],  # Tags
    'privacy_status': 'unlisted',                # 'public', 'unlisted', or 'private'
    'category_id': '10',                         # 10=Music, 22=Shorts
}

# ═══════════════════════════════════════════════════════════════

def upload():
    """Upload video with config above"""
    uploader = YouTubeUploader(
        credentials_file='credentials.json',
        token_file='token.pickle'
    )

    # Authenticate (opens browser first time only)
    print("[INFO] Authenticating...")
    uploader.authenticate()

    # Upload
    print("[INFO] Uploading video...")
    video_id = uploader.upload_video(**video_config)

    if video_id:
        print(f"\n{'='*60}")
        print(f"[OK] SUCCESS!")
        print(f"{'='*60}")
        print(f"Video ID: {video_id}")
        print(f"Watch: https://youtube.com/watch?v={video_id}")
        print(f"{'='*60}\n")
    else:
        print("\n[FAIL] FAILED - Check errors above\n")

if __name__ == '__main__':
    upload()
