#!/usr/bin/env python3
"""
SUNO → YouTube Integration
Automatically uploads clips from SUNO inbox to YouTube with OAuth
"""

import os
from pathlib import Path
from upload_video import YouTubeUploader

class SUNOYouTubeIntegration:
    """
    Integrates SUNO clip generation with YouTube uploads.
    Handles OAuth caching, batch uploads, and error recovery.
    """

    def __init__(self, suno_clips_dir='../clips/inbox',
                 credentials_file='credentials.json',
                 token_file='token.pickle'):
        """
        Initialize SUNO-YouTube bridge.

        Args:
            suno_clips_dir: Path to SUNO clips inbox
            credentials_file: Path to Google OAuth credentials
            token_file: Path to cached auth token
        """
        self.suno_clips_dir = Path(suno_clips_dir)
        self.uploader = YouTubeUploader(credentials_file, token_file)
        self.authenticated = False

    def authenticate_once(self):
        """Authenticate once, reuse token for all uploads"""
        if not self.authenticated:
            print("[INFO] Authenticating with YouTube...")
            self.uploader.authenticate()
            self.authenticated = True
            print("[OK] Authenticated! Token will be reused for all uploads.\n")

    def get_clip_files(self):
        """Get all video files from SUNO clips inbox"""
        if not self.suno_clips_dir.exists():
            print(f"[WARNING] Clips directory not found: {self.suno_clips_dir}")
            return []

        video_extensions = {'.mp4', '.mov', '.avi', '.mkv', '.webm'}
        clips = [
            f for f in self.suno_clips_dir.iterdir()
            if f.suffix.lower() in video_extensions
        ]

        return sorted(clips)

    def upload_clip(self, clip_path, title=None, description=None,
                   tags=None, privacy_status='unlisted'):
        """
        Upload a single clip to YouTube.

        Args:
            clip_path: Path to video file
            title: Video title (auto-generated if not provided)
            description: Video description
            tags: List of tags
            privacy_status: 'public', 'unlisted', or 'private'

        Returns:
            Video ID if successful
        """
        clip_path = Path(clip_path)

        # Auto-generate title from filename if not provided
        if not title:
            title = clip_path.stem.replace('_', ' ').replace('-', ' ')
            if len(title) > 100:
                title = title[:97] + '...'

        # Default description
        if not description:
            description = f"Generated by SUNO AI\n{clip_path.name}"

        # Default tags
        if not tags:
            tags = ['suno', 'ai-music', 'ai-generated']

        return self.uploader.upload_video(
            file_path=str(clip_path),
            title=title,
            description=description,
            tags=tags,
            category_id='10',  # Music
            privacy_status=privacy_status
        )

    def upload_all_clips(self, dry_run=False):
        """
        Upload all clips from SUNO inbox to YouTube.

        Args:
            dry_run: If True, only list clips without uploading

        Returns:
            Dict with upload results
        """
        clips = self.get_clip_files()

        if not clips:
            print("[INFO] No clips found in inbox")
            return {'total': 0, 'uploaded': 0, 'failed': 0}

        print(f"[INFO] Found {len(clips)} clips to upload\n")

        if dry_run:
            print("[DRY RUN MODE] Would upload:")
            for clip in clips:
                print(f"  - {clip.name}")
            return {'total': len(clips), 'uploaded': 0, 'failed': 0}

        # Authenticate once
        self.authenticate_once()

        results = {
            'total': len(clips),
            'uploaded': 0,
            'failed': 0,
            'videos': []
        }

        for i, clip in enumerate(clips, 1):
            print(f"[{i}/{len(clips)}] Uploading: {clip.name}")

            video_id = self.upload_clip(clip_path=clip)

            if video_id:
                results['uploaded'] += 1
                results['videos'].append({
                    'file': clip.name,
                    'video_id': video_id,
                    'url': f"https://youtube.com/watch?v={video_id}"
                })
                print(f"[OK] https://youtube.com/watch?v={video_id}\n")
            else:
                results['failed'] += 1
                print(f"[FAIL] Failed\n")

        # Summary
        print(f"\n{'='*60}")
        print(f"UPLOAD COMPLETE")
        print(f"{'='*60}")
        print(f"Total: {results['total']} | Uploaded: {results['uploaded']} | Failed: {results['failed']}")
        if results['videos']:
            print(f"\nUploaded videos:")
            for v in results['videos']:
                print(f"  {v['url']}")
        print(f"{'='*60}\n")

        return results


def main():
    """Example: Upload all SUNO clips"""
    integration = SUNOYouTubeIntegration(
        suno_clips_dir='../clips/inbox',
        credentials_file='credentials.json',
        token_file='token.pickle'
    )

    # Dry run (just list clips)
    print("[INFO] DRY RUN - Listing clips\n")
    integration.upload_all_clips(dry_run=True)

    # Real upload (uncomment to run)
    # print("[INFO] STARTING UPLOADS\n")
    # results = integration.upload_all_clips(dry_run=False)


if __name__ == '__main__':
    main()
